config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  namespace :api, :defaults => {:format => :json} do
    resources :invoices, only: [:create]
  end

  get '*path', to: 'pages#index', via: :all
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  after_create :check_new_product

  class << self
    def insert_all(...)
      result = super(...)
      check_new_product_bulk(result)
      result
    end

    def upsert_all(...)
      result = super(...)
      check_new_product_bulk(result)
      result
    end

    def check_new_product_bulk(result)
      Product.create_product_if_not_exist(result.rows)
    end

    def cost_calculator(product_code, nth)
      result = {
        status: false,
        message: '',
        invoice: nil,
        value: nil
      }

      fifo_result = fifo(product_code, nth)

      if fifo_result.instance_of?(String)
        result[:message] = fifo_result
      else
        result[:status] = true
        result[:invoice] = fifo_result
        result[:value] = fifo_result.sum / fifo_result.quantity
      end

      result
    end

    def fifo(product_code, nth)
      invoices = Invoice.where(product_code: product_code).order(invoice_date: :desc)
      sum = 0

      return 'Product doesn\'t exist.' if invoices.count.zero?
      return 'Invoice cannot be found' if nth > invoices.sum(:quantity)

      invoices.each do |invoice|
        sum += invoice.quantity
        return invoice if sum >= nth
      end

      'En error occured.'
    end
  end

  private

  def check_new_product
    Product.create_product_if_not_exist([[product_code, definition]])
  end
end

app/controllers/api/invoices_controller.rb
class Api::InvoicesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  before_action :authenticate_with_api_key

  def create
    if invoice_params['data'].nil?
      render json: {
        autenthicated: true,
        message: 'No record provided.'
      }
      return
    end

    result = Invoice.insert_all(invoice_params['data'], returning: %w[product_code definition])

    render json: {
      autenthicated: true,
      result: result
    }
  end

  private

  def authenticate_with_api_key
    unless api_key_params['api_key'] == 'api_key'
      render json: {
        autenthicated: false,
        message: 'Wrong API key.'
      }
      return
    end
  end

  def api_key_params
    params.permit(:api_key)
  end

  def invoice_params
    params.permit(:data => %i[
                invoice_number
                pen_number
                quantity
                tax_kdv
                tax_otv
                definition
                value_date
                invoice_date
                sum
                product_code
                created_at
                updated_at
              ])
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[show edit update destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show; end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit; end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def invoice_params
    params.require(:invoice).permit(:invoice_number, :pen_number, :quantity, :tax_kdv, :tax_otv, :definition,
                                    :value_date, :sum, :product_id)
  end
end

app/helpers/api/invoices_helper.rb
module Api::InvoicesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :invoice_number %>
    <%= form.number_field :invoice_number %>
  </div>

  <div class="field">
    <%= form.label :pen_number %>
    <%= form.number_field :pen_number %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :tax_kdv %>
    <%= form.text_field :tax_kdv %>
  </div>

  <div class="field">
    <%= form.label :tax_otv %>
    <%= form.text_field :tax_otv %>
  </div>

  <div class="field">
    <%= form.label :definition %>
    <%= form.text_field :definition %>
  </div>

  <div class="field">
    <%= form.label :value_date %>
    <%= form.date_select :value_date %>
  </div>

  <div class="field">
    <%= form.label :sum %>
    <%= form.text_field :sum %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice number</th>
      <th>Pen number</th>
      <th>Quantity</th>
      <th>Tax kdv</th>
      <th>Tax otv</th>
      <th>Definition</th>
      <th>Value date</th>
      <th>Sum</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_number %></td>
        <td><%= invoice.pen_number %></td>
        <td><%= invoice.quantity %></td>
        <td><%= invoice.tax_kdv %></td>
        <td><%= invoice.tax_otv %></td>
        <td><%= invoice.definition %></td>
        <td><%= invoice.value_date %></td>
        <td><%= invoice.sum %></td>
        <td><%= invoice.product_id %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice number:</strong>
  <%= @invoice.invoice_number %>
</p>

<p>
  <strong>Pen number:</strong>
  <%= @invoice.pen_number %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @invoice.quantity %>
</p>

<p>
  <strong>Tax kdv:</strong>
  <%= @invoice.tax_kdv %>
</p>

<p>
  <strong>Tax otv:</strong>
  <%= @invoice.tax_otv %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @invoice.definition %>
</p>

<p>
  <strong>Value date:</strong>
  <%= @invoice.value_date %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @invoice.sum %>
</p>

<p>
  <strong>Product:</strong>
  <%= @invoice.product_id %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>